sudo: required
language: go
go:
- 1.12.x
services:
- docker
before_install:
- sudo rm -f /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- go get -u github.com/go-bindata/go-bindata/...
- go get github.com/elazarl/go-bindata-assetfs/...
- go get golang.org/x/lint/golint
- curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
  | sh -s -- -b . v1.16.0
- sudo mv golangci-lint /usr/local/bin
- ls /home/travis/gopath/bin
- "/usr/local/bin/docker-compose up -d"
cache:
  directories:
  - node_modules
install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
  && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
  install 10.16.0
- node --version
- npm --version
- npm install -g @angular/cli@8.0.2
- go mod vendor
script:
- cd $TRAVIS_BUILD_DIR
- "./build.sh"
- "./kaaryasthan -migrate"
- "./runtests.sh"
branches:
  except:
  - "/^exp-.*$/"
after_success:
- curl -s https://gist.githubusercontent.com/baijum/37354d9de3b3dd38533f5d74b709086a/raw/merge.sh
  | bash
env:
  global:
  - secure: gPBpvisrHtuzC4N6FdcfIid04iXaL92t5rikaA6IgfEMsIfRhzyTdskbpvCZN+ocRHZwBIVsCEuQEEk/ZRK0jBuoUbre0cIVZ5gh8c5AgkDi7d6RIj+iGFOOPc+HCm9XBvnwcd0YKUwqAPPuXfAW2feYsV7S3vB//hveEnDa9FmSvbKmTwefYPghNpxz5uOGraHqWAiVghRHVPhmjF1ox6Tg3LKhKBNvGRsEZoj3mPnzi7ACO/jLSsOUCMl4k2+RAXfeVrCl9tEqMRG0+FrAZGhvvIk4Qu22KViJcHzFpx0zNx0A3FJpH8WMSYd6Zj7TEFj3rq1cl/pTrIKMgmPdlfwgKShEQsAGhbkXfVxzVFSeqI6jbxk7eTIjig3u+v9tSLK4OdPGjhE5kU14o36Wtg5LENgk6g7+ru8FGBKL936LvIpmx3Qu50AWgXIeHmyO2WrrT8YlmaBH9VLk/ZfLSx28oN9JGGMH2FDbk2UKAIoEcDo0Bh3fou+V6hnjDaiMUVGPE1HY5s4SnVLwLuQ2KsQXe1E3bvSk4d4IS8dICBm8cFglPWCgloRse2htqaTQhE2/o2KZsLQG/XSyeD39Ds9BGlmqGb2+RZ811wgokjdh2dy3EeP3Ty2p52a337eGR0CW91szkgnNLWYZ6BKEFPIY34EoUS2Y0ng/V1sIylY=
  - GO111MODULE=on
